// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rxxkqvenndgkrezqaxar.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4eGtxdmVubmRna3JlenFheGFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTExMDIsImV4cCI6MjA2NTQ4NzEwMn0.fc2JDWFrbbfESAjZWY9TZwwZiPos4GRezIFGz5CtIEw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);